on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download Unicom address list
      run: |
        DATE=$(date +"%Y.%m")
        DATE2=$(date +"%Y-%m-%d")
        wget http://www.tcp5.com/list/${DATE}/unicom${DATE}.rsc -O unicom.rsc
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        message: "Update Unicom address list as of ${DATE}"
