name: Download and Commit Unicom Address List

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download Unicom address list
      run: |
        DATE=$(date +"%Y-%m-%d")
        wget http://www.tcp5.com/list/$(date +"%Y.%m")/unicom$(date +"%Y-%m-%d"-12).rsc -O unicom.rsc
    - name: Commit & Push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b main
        git add unicom.rsc
        git commit -m "Update Unicom address list as of ${DATE}"
        git push origin main
        echo "Done"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
